require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClassroomsController do

  def mock_classroom(stubs={})
    @mock_classroom ||= mock_model(Classroom, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all classrooms as @classrooms" do
      Classroom.stub(:all) { [mock_classroom] }
      get :index
      assigns(:classrooms).should eq([mock_classroom])
    end
  end

  describe "GET show" do
    it "assigns the requested classroom as @classroom" do
      Classroom.stub(:find).with("37") { mock_classroom }
      get :show, :id => "37"
      assigns(:classroom).should be(mock_classroom)
    end
  end

  describe "GET new" do
    it "assigns a new classroom as @classroom" do
      Classroom.stub(:new) { mock_classroom }
      get :new
      assigns(:classroom).should be(mock_classroom)
    end
  end

  describe "GET edit" do
    it "assigns the requested classroom as @classroom" do
      Classroom.stub(:find).with("37") { mock_classroom }
      get :edit, :id => "37"
      assigns(:classroom).should be(mock_classroom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created classroom as @classroom" do
        Classroom.stub(:new).with({'these' => 'params'}) { mock_classroom(:save => true) }
        post :create, :classroom => {'these' => 'params'}
        assigns(:classroom).should be(mock_classroom)
      end

      it "redirects to the created classroom" do
        Classroom.stub(:new) { mock_classroom(:save => true) }
        post :create, :classroom => {}
        response.should redirect_to(classroom_url(mock_classroom))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved classroom as @classroom" do
        Classroom.stub(:new).with({'these' => 'params'}) { mock_classroom(:save => false) }
        post :create, :classroom => {'these' => 'params'}
        assigns(:classroom).should be(mock_classroom)
      end

      it "re-renders the 'new' template" do
        Classroom.stub(:new) { mock_classroom(:save => false) }
        post :create, :classroom => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested classroom" do
        Classroom.stub(:find).with("37") { mock_classroom }
        mock_classroom.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :classroom => {'these' => 'params'}
      end

      it "assigns the requested classroom as @classroom" do
        Classroom.stub(:find) { mock_classroom(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:classroom).should be(mock_classroom)
      end

      it "redirects to the classroom" do
        Classroom.stub(:find) { mock_classroom(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(classroom_url(mock_classroom))
      end
    end

    describe "with invalid params" do
      it "assigns the classroom as @classroom" do
        Classroom.stub(:find) { mock_classroom(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:classroom).should be(mock_classroom)
      end

      it "re-renders the 'edit' template" do
        Classroom.stub(:find) { mock_classroom(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested classroom" do
      Classroom.stub(:find).with("37") { mock_classroom }
      mock_classroom.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the classrooms list" do
      Classroom.stub(:find) { mock_classroom }
      delete :destroy, :id => "1"
      response.should redirect_to(classrooms_url)
    end
  end

end
